### DISCUSSION TITLE
issue with image entrypoint.sh

### DISCUSSION THREAD

**Discussion by maquino1985** [tiangolo/meinheld-gunicorn-flask-docker#161] [Questions] [answered]
I was having strange behavior for a long time, spending weeks trying to debug very strange connectivity issues with hanging queries and a particular graphql endpoint. nothing about the issue itself had any explainable cause and finally i tried loading gunicorn manually and magically all of the issues vanished.  I looked at the entry_point.sh and saw that some of the environment variables that should have been set were all blank: APP_MODULE and GUNICORN_CONF 

the environment from my docker-compose is unchanged. the only thing I've changed is adding in the custom entry point.  Is there something obviously _missing_ or incorrect that would explain why the default entrypoint would have problems?

The application is in /app/wsgi.py and the app module name is app, e.g. 

```python
from espresso import app

app.settings.wsgi_mode = True

import webapp.web.dispatch_application_route
```

```yaml
    image: {image_tag}
    entrypoint: "gunicorn wsgi:app -c gunicorn_conf.py"
    ports:
      - "5000:5000"
    volumes:
      - ./env.staging.json:/var/tmp/env.json
      - ./gunicorn_conf.py:/app/gunicorn_conf.py
    environment:
      - LOG_LEVEL=debug
      - MODULE_NAME=wsgi
      - FLASK_CONFIG=development
      - FLASK_ENV=development
      - ENV_FILE=/var/tmp/env.json
    networks:
      internal-network:
        aliases:
          - "backend"
      outside-world:
```
