### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT - How do I increase default timeout seconds?

### ISSUE THREAD

**Issue by ethanopp** [tiangolo/meinheld-gunicorn-flask-docker#16]
It seems that the default is set to 30, and whenever any process runs over this threshold it gets killed and this error is thrown:
`[2019-09-22 09:26:01 -0400] [1] [CRITICAL] WORKER TIMEOUT (pid:16)    `

Per gunicorn's documentation, the `--timeout INT` argument can be passed, however when updating my docker compose to the following, I am still receiving the above error message after anything runs for longer than 30 seconds.

```
  fitly:
    build:
      context: ./dockercontrol-master
      dockerfile: fitly-dockerfile
    container_name: fitly
    restart: always
    depends_on:
      - mariadb
      - letsencrypt
    ports:
      - "8050:80"
    environment:
      - MODULE_NAME=index
      - VARIABLE_NAME=app
      - TZ=America/New_York
      - GUNICORN_CMD_ARGS='--timeout 60'
      - PUID=1001
      - PGID=100
    volumes:
      - /share/CACHEDEV2_DATA/Container/Fitly/config.ini:/app/config.ini
      - /share/CACHEDEV2_DATA/Container/Fitly/log.log:/app/log.log
      - /share/CACHEDEV2_DATA/Container/LetsEncrypt/keys:/app/keys
```

Is there another way to update the timeout?

I also saw some posts about trying to use with gevents but got the same results, although I'm not really sure this argument is truly being passed into the docker container either:
`- GUNICORN_CMD_ARGS='--worker-class gevent --timeout 60'`

I'm also running this behind NGINX, and have tried putting the following in the conf:
```
    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_fitly fitly;
        proxy_pass http://$upstream_fitly:80;
    }
```
Where in the proxy.conf I have the following lines:
```
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
```
...Still no dice

**Comment by ethanopp** [comment]
For anyone else out there, it seems you can simply define a 'timeout' variable in the gunicorn_conf.py...

Similarly, adding the following line to that gunicorn_conf.py file will let you pass an environment from the docker compose:
`timeout = os.getenv("TIMEOUT", 30)`


...still unsure why passing through the cmd_args wasn't working, but this workaround does the trick!

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:

**Comment by Shane-Neeley** [comment]
Is there any way to adjust the timeout without a custom gunicorn_conf.py file?

**Comment by ethanopp** [comment]
@Shane-Neeley just define the environment variable for TIMEOUT:
```
  fitly-slap:
    build:
      context: ./dockercontrol-master
      dockerfile: fitly-slap-dockerfile
    container_name: fitly
    restart: always
    depends_on:
      - letsencrypt
    ports:
      - "8050:80"
    environment:
      - MODULE_NAME=src.fitly.app
      - VARIABLE_NAME=server
      - TZ=America/New_York
      - TIMEOUT=1200
      - PUID=1000
      - PGID=100
      - DASH_DEBUG=true
    volumes:
      - /share/CACHEDEV2_DATA/Container/Fitly-Slap:/app/config
      - /share/CACHEDEV2_DATA/Container/LetsEncrypt/keys:/app/keys
```
